name: datamate
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.8
  - bokeh=2.4.3   
  - panel=0.14.1
  - pip=22.3.1
  - pip:
    - holoviews==1.15.4
    - hvplot==0.8.2
    - seaborn==0.12.2
    - dask[complete]==2022.7.0
    - networkx==2.8.4
    - pyarrow==8.0.0
